language: erlang
otp_release:
- 17.0
before_install:
- git clone https://github.com/elixir-lang/elixir
- cd elixir
- git checkout v0.14.1
- cd ..
- make -C elixir
before_script: "export PATH=`pwd`/elixir/bin:$PATH"
script: "MIX_ENV=test mix do local.hex, deps.get, test"
